# Atom-Atom Mapping

Atom-atom mapping can help chemists and biologist to get a better understanding of the reaction mechanisms and provide clues for lead compound optimization for medicinal chemists. In this example, we are going to use two sided permutation Procrustes, which has been implemented `procrustes.permutation_2sided`.

The example we are going to use is shown below, which is the atom-atom mapping between 3,3‐dimethylpent‐1‐en‐4‐yne and but‐1‐en‐3‐yne. For clarity, we denote but‐1‐en‐3‐yne molecule **A** and 3,3‐dimethylpent‐1‐en‐4‐yne molecule **B**. What would be most reasonable mapping? If it is not mapping the double bounds and triple bonds respectively, it is not a good matching based on our chemical knowledge.

![Fig. 1 Two organic compounds for atom-atom mapping](before_mapping.png "Fig. 1 Two organic compounds for atom-atom mapping")

In order to figure the mapping relationship, one needs to represent the molecules in a matrix format. We will save the nuclear charge as the diagonal elements and the bond orders for off-diagonal ones, which has been depicted below. In this way, the matrix $A \in R^{7\times7}$ and the matrix $B \in R^{4 \times4}$ are built, both of which are symmetric. The atoms are also labeled for later discussion.

![Fig. 2 Graphical representation for two molecules.](data.png)

In [40]:
# import required libraries
from __future__ import absolute_import, division, print_function
import numpy as np
from procrustes import permutation_2sided, utils

Now we have two matrices $A$ and $B$ for two molecules,

In [64]:
# Define molecule A, but‐1‐en‐3‐yne
A = np.array([[6, 3, 0, 0],
              [3, 6, 1, 0],
              [0, 1, 6, 2],
              [0, 0, 2, 6]])

In [65]:
# Define molecule B, 3,3‐dimethylpent‐1‐en‐4‐yne
B = np.array([[6, 3, 0, 0, 0, 0, 0],
              [3, 6, 1, 0, 0, 0, 0],
              [0, 1, 6, 1, 0, 1, 1],
              [0, 0, 1, 6, 2, 0, 0],
              [0, 0, 0, 2, 6, 0, 0],
              [0, 0, 1, 0, 0, 6, 0],
              [0, 0, 1, 0, 0, 0, 6]])

In [66]:
B

array([[6, 3, 0, 0, 0, 0, 0],
       [3, 6, 1, 0, 0, 0, 0],
       [0, 1, 6, 1, 0, 1, 1],
       [0, 0, 1, 6, 2, 0, 0],
       [0, 0, 0, 2, 6, 0, 0],
       [0, 0, 1, 0, 0, 6, 0],
       [0, 0, 1, 0, 0, 0, 6]])

In [67]:
_, _, U, e_opt = permutation_2sided(
    A, B, transform_mode='single_undirected',
    remove_zero_col=False, remove_zero_row=False)

In [68]:
# the permutation matrix
U

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0.]])

In [69]:
B

array([[12,  9,  6,  6,  6,  6,  6],
       [ 9, 12,  7,  6,  6,  6,  6],
       [ 6,  7, 12,  7,  6,  7,  7],
       [ 6,  6,  7, 12,  8,  6,  6],
       [ 6,  6,  6,  8, 12,  6,  6],
       [ 6,  6,  7,  6,  6, 12,  6],
       [ 6,  6,  7,  6,  6,  6, 12]])

The new matrix of molecule A can be obtained with the permutation operation.

In [60]:
# the padded matrix A
temp_A, temp_B = utils.zero_padding(A, B)

# Compute the transformed molecule A
new_A = np.dot(U.T, np.dot(temp_A, U))

In [61]:
print(new_A)

[[6. 3. 0. 0. 0. 0. 0.]
 [3. 6. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 6. 2. 0. 0.]
 [0. 0. 0. 2. 6. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [62]:
temp_B

array([[12,  9,  6,  6,  6,  6,  6],
       [ 9, 12,  7,  6,  6,  6,  6],
       [ 6,  7, 12,  7,  6,  7,  7],
       [ 6,  6,  7, 12,  8,  6,  6],
       [ 6,  6,  6,  8, 12,  6,  6],
       [ 6,  6,  7,  6,  6, 12,  6],
       [ 6,  6,  7,  6,  6,  6, 12]])

In [63]:
B

array([[12,  9,  6,  6,  6,  6,  6],
       [ 9, 12,  7,  6,  6,  6,  6],
       [ 6,  7, 12,  7,  6,  7,  7],
       [ 6,  6,  7, 12,  8,  6,  6],
       [ 6,  6,  6,  8, 12,  6,  6],
       [ 6,  6,  7,  6,  6, 12,  6],
       [ 6,  6,  7,  6,  6,  6, 12]])